### ISSUE TITLE
JS not loading

### ISSUE THREAD

**Issue by petarBozovicWSM** [leytech/Leytech_PrototypeUpdate#6]
I'm having this issue where it does not load the JS on other website and store views, aside from the main. Is it just me? 

Thank you in advance

**Comment by bluec** [comment]
Hi @petarBozovicWSM thanks for the report. Must admit I haven't tested this on multi-store setup but assumed it would work. I will do so if I have chance. Meantime can you just confirm you have cleared caches etc, and have you tried configuring it in the specific / individual store scopes rather than just globally?

**Comment by petarBozovicWSM** [comment]
Hi @bluec, thank you for taking your time out! That was what i tried at first, enabling it for each scope and also clearing the cache. I have been looking thru it, but im not sure why it wont load on the other scopes, its quite interesting.

**Comment by petarBozovicWSM** [comment]
I retract my statement, its working. Sorry!!
